GET https://jsonplaceholder.typicode.com/posts/101

###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "userId": 1,
    "id": 101,
    "title": "temporibus sit alias delectus eligendi possimus magni",
    "body": "quo deleniti praesentium dicta non quod\naut est molestias\nmolestias et officia quis nihil\nitaque dolorem quia"
}

###
PATCH https://jsonplaceholder.typicode.com/posts/101
Content-Type: application/json

{
    "title": "updated title"
}

###
PUT https://jsonplaceholder.typicode.com/posts/101
Content-Type: application/json

{
    "userId": 1,
    "id": 101,
    "title": "updated title",
    "body": "updated body"
}

###
DELETE https://jsonplaceholder.typicode.com/posts/101